import { Josefin_Sans } from "next/font/google";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Josef= Josefin_Sans({
  subsets: ['latin'],
  weight: ["100", "200" , "300", "400", "500" ,  "600", "700"]
})


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={Josef.className}>{children}</body>
    </html>
  );
}
